// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = "OpenWrt";    // Network SSID (name)
const char PASS[]     = "mvthsstudent";    // Network password (use for WPA, or use as key for WEP)

void onHoursChange();

CloudTime hours;

void initProperties(){

  ArduinoCloud.addProperty(hours, READWRITE, ON_CHANGE, onHoursChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
